version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: task_system
    ports:
      - "5444:5432"
#    volumes:
#      - :/var/lib/postgresql/data

